package com.Page_Repositary;
import org.openqa.selenium.By;

public class PageRepositary_ProjectModule {
       
       
	public By PopupDisplayedCovid = By.xpath("//button[normalize-space()='Remind Me Later']");
	public By OkBtnCovid = By.xpath("//button[normalize-space()='Remind Me Later']");
	public By PopupDisplayedDesktop = By.xpath("//*[@id=\"modal-basic-title\" and text()=' Desktop Notifications ']");
	public By OkBtnDesktop = By.xpath("//div/button[2][text()='OK']");
//clients
       public By clickOnproject= By.xpath("//span[text()='Projects']");
       public By ProjectDashboard=By.xpath("//span[normalize-space()='Dashboard']");
       public By AllocatedProjects = By.xpath("//h5[normalize-space()='Allocated Projects']");
       public By closebutton = By.xpath("//button[normalize-space()='×']");
       public By Clickonclients= By.xpath("//span[normalize-space()='Clients']");
       public By Clientlist= By.xpath("//span[normalize-space()='Client List']");
       public By Clickonclient = By.xpath("//td[@data-title='Client Name']");
       public By ClientRequest = By.xpath("//span[normalize-space()='Client Request']");
       public By Savedclientpage = By.xpath("//a[contains(@href,'#/project/savedClientRequestList')]");
       public By selectsavedclient = By.xpath("//td[@data-title='Client Name']");
       public By submittedclientpage = By.xpath("//a[contains(@href,'#/project/submittedClientRequestList')]");
       public By allocatedprojectgraph = By.xpath("//div[contains(text(),'Allocated Projects')]");
       public By hoursgraph = By.xpath("//div[contains(text(),'Project Allocation Hours Vs Submitted Hours')]");
       public By projectutilizationgraph = By.xpath("//h4[normalize-space()='Project Utilization(Last 3 months)']");
       public By Clientnamecolumn= By.xpath("//span[normalize-space()='Client Name']");
       public By Clientcodecolumn= By.xpath("//span[normalize-space()='Client Code']");
       public By Clientcontactpersoncolumn= By.xpath("//span[normalize-space()='Contact Person']");
       public By Clientcontactnumbercolumn= By.xpath("//span[normalize-space()='Contact Number']");
       public By clientcontactemailcolumn= By.xpath("//span[normalize-space()='Contact Email']");
       public By clientcompanywebsitecolumn= By.xpath("//span[normalize-space()='Company Website']");
       public By clientaddresscolumn= By.xpath("//span[normalize-space()='Address Line 1']");
       public By totalitems= By.xpath("//div[@class='t-foot-lt']");
       public By searchicon= By.xpath("//button[@id='dLabel']//i[contains(@class,'i-Magnifi-Glass1')]");
       public By downloadicon= By.xpath("//button[@class='btn btn-primary btn-download-file ng-star-inserted']");
       public By addnewbutton= By.xpath("//button[normalize-space()='Add New']");
       public By pagination= By.xpath("//li[@class='current ng-star-inserted']");
       public By clientcountrycolumn= By.xpath("//span[normalize-space()='Country']");
       public By clientzipcodecolumn= By.xpath("//span[normalize-space()='Zip Code']");
       public By clientrequestedbycolumn= By.xpath("//span[normalize-space()='Requested By']");
       public By inputclientname= By.xpath("//input[@id='ClientName']");
       public By inputcontactperson = By.xpath("//input[@id='ContactPerson']");
       public By inputcontactemail = By.xpath("//input[@id='ContactEmail']");
       public By indiacountry = By.xpath("//span[contains(text(),'India')]");
       public By inputaddress = By.xpath("//input[@id='AddressLine1']");
       public By selectcountry = By.xpath("//input[@id='Country']");
       public By selectaccountmanager = By.xpath("//input[@id='AcntMngr']");
       public By aanacaccountmanager = By.xpath("//span[contains(text(),'Aana C')]");
       public By selectbusineesunit=By.xpath("//input[@id='BusinessUnitName']");
       public By indiabusinessunit=By.xpath("//span[contains(text(),'Speridian India')]");
       public By savebutton = By.xpath("//button[normalize-space()='Save']");
       public By closebuttontext = By.xpath("//button[normalize-space()='Close']");
       public By checkbox = By.xpath("//input[@id='IsIHereBy']");
       public By selectprojectsector=By.xpath("//select[@id='ProjectSectorId']");       
       public By publicsector = By.xpath("//option[@value='2: 2']");
       public By submitbutton=By.xpath("//button[normalize-space()='Submit']");
       public By inputzipcode=By.xpath("//input[@id='ZipCode']");
       public By clientnameheading =By.xpath("//label[normalize-space()='Client Name']");
       public By clientcodeheading =By.xpath("//label[normalize-space()='Client Code']");
       public By contactpersonheading =By.xpath("//label[normalize-space()='Contact Person']");
       public By contactnumberheading =By.xpath("//label[normalize-space()='Contact Number']");
       public By contactemailheading =By.xpath("//label[normalize-space()='Contact Email']");
       public By companywebsiteheading =By.xpath("//label[normalize-space()='Company Website']");
       public By address1heading =By.xpath("//label[normalize-space()='Address Line 1']");
       public By address2heading =By.xpath("//label[normalize-space()='Address Line 2']");
       public By address3heading =By.xpath("//label[normalize-space()='Address Line 3']");
       public By countryheading =By.xpath("//label[normalize-space()='Country']");
       public By zipcodeheading =By.xpath("//label[normalize-space()='Zip Code']");
       public By accountmanagerheading =By.xpath("//label[normalize-space()='Account Manager']");
       public By salesmanagerheading =By.xpath("//label[normalize-space()='Sales Manager']");
       public By salesexecutiveheading =By.xpath("//label[normalize-space()='Sales executive']");
       public By businessunitheading =By.xpath("//label[normalize-space()='Business Unit']");
       public By gstnoheading =By.xpath("//label[normalize-space()='GSTIN Number']");
       public By projectsectorheading =By.xpath("//label[normalize-space()='Project Sector Type']");
       public By Logoupload = By.xpath("//div[contains(@title,'Please click here')]");
       public By searchfield = By.xpath("//input[@id='SearchValue']");
       public By searchbutton=By.xpath("//div[@class='modal-footer']//button[@id='dLabel']");
       public By searchclose=By.xpath("//i[@class='i-Close']");
       public By addDocumentbutton = By.xpath("//mat-panel-title[@class='mat-expansion-panel-header-title']");
       public By attachbutton = By.xpath("//tbody/tr[1]/td[6]/div[1]/div[1]/i[1]");
       public By datepick = By.xpath("//*[name()='path' and contains(@d,'M19 3h-1V1')]");
       public By nextmonth = By.xpath("//button[@aria-label='Next month']");
       public By date = By.xpath("//div[normalize-space()='30']");
       public By choosefile = By.xpath("//input[@id='chooseFile1']");
       public By uploadbutton = By.xpath("//button[normalize-space()='Upload']");
       public By attachdoc2 = By.xpath("//body[1]/app-root[1]/block-ui[1]/app-admin-layout-sidebar-large[1]/div[1]/div[3]/app-client-add[1]/div[1]/div[3]/div[1]/form[2]/div[1]/mat-accordion[1]/mat-expansion-panel[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[2]/td[6]/div[1]/div[1]");
//projects
       public By projects=By.xpath("//span[@class='item-name'][normalize-space()='Projects']");
       public By Projectlist=By.xpath("//a[@href='#/project/projectList']//span[@class='item-name lvl1']");
       public By projectcodecolumn=By.xpath("//span[normalize-space()='Project Code']");
       public By projectnamecolumn=By.xpath("//span[normalize-space()='Project Name']");
       public By clientnamecolumn=By.xpath("//span[normalize-space()='Client Name']");
       public By projectdirectorcolumn=By.xpath("//span[normalize-space()='Project Director']");
       public By projectmanagercolumn=By.xpath("//span[normalize-space()='Project Manager']");
       public By billabilitycolumn=By.xpath("//span[normalize-space()='Billability']");
       public By projecttypecolumn=By.xpath("//span[normalize-space()='Project Type']");
       public By expectstartdatecolumn=By.xpath("//span[normalize-space()='Expected StartDate']");
       public By startdatecolumn=By.xpath("//span[normalize-space()='Start Date']");
       public By selectproject = By.xpath("//span[@class='link ng-star-inserted']");
       public By createproject = By.xpath("//span[normalize-space()='Create Project']");
       public By projectclientname=By.xpath("//input[@id='ClientName']");
       public By clientoneselect = By.xpath("//span[contains(text(),'Clientone')]");
       public By projectname=By.xpath("//input[@id='ProjectName']");
       public By projectbusinessunit=By.xpath("//input[@id='BusinessUnitSearch']");
       public By projectbusinessunitselect=By.xpath("//span[contains(text(),'Speridian India')]");
       public By projectdivision=By.xpath("//input[@id='DivisionName']");
       public By projectdivisionselect=By.xpath("//span[contains(text(),'CRM/CX')]"); 
       public By projectdepartment=By.xpath("//input[@id='ProjectDepartment']");
       public By projectdepartmentselect=By.xpath("//span[contains(text(),'Account Management')]");
       public By projecttechnology=By.xpath("//input[@id='TechnologyName']");
       public By projecttechnologyselect=By.xpath("//span[contains(text(),'Accounts and Admin')]");
       public By projecttype=By.xpath("//select[@id='ProjectType']");
       public By projecttypefixedprice=By.xpath("//option[normalize-space()='Fixed Price']");
       public By projectbillablehours=By.xpath("//div[@class='col-lg-2 ng-star-inserted']//input[@id='MaxBillableHours']");
       public By projectbillabledropdown=By.xpath("//select[@id='DailyWorkingHours']");
       public By projectbillableselect=By.xpath("//option[@value='2: 2']");
       public By projectstartdate=By.xpath("(//div/mat-datepicker-toggle/button[@aria-label='Open calendar'])[1]");
       public By projectenddate=By.xpath("(//div/mat-datepicker-toggle/button[@aria-label='Open calendar'])[2]");
       public By projectstartdateselect=By.xpath("//div[normalize-space()='25']");
       public By projectenddateselect=By.xpath("//div[normalize-space()='24']");
       public By projectcurrentphase=By.xpath("//input[@id='CurrentPhase']");
       public By projectcurrentphaseselect=By.xpath("//span[contains(text(),'Design')]");
       public By projectdirector=By.xpath("//input[@id='ProjectDirector']");
       public By searchperson = By.xpath("//input[@placeholder='Search..']");
       public By projectdirectorselect=By.xpath("//td[normalize-space()='Clement Joseph']");
       public By projectmanager=By.xpath("//input[@id='ProjectManager']");
       public By projectmanagerselect=By.xpath("//td[normalize-space()='Clement Joseph']");
       public By projectaccountmanager=By.xpath("//input[@id='AccountManager']");
       public By projectaccountmanagerselect=By.xpath("//td[normalize-space()='A Aare']");
       public By projectsaveandnext=By.xpath("//button[@name='save']");
       public By projectbillingdetail=By.xpath("//mat-panel-title[normalize-space()='Billing Details']");
       public By okbutton = By.xpath("//button[normalize-space()='OK']");
       public By billingsave = By.xpath("//button[@name='save']");
       public By currencydrop = By.xpath("//select[@id='SOWCurrency']");
       public By ind = By.xpath("//option[@value='170: 1']");
       public By currencyvalue = By.xpath("//input[@id='SOWContractValue']");
       public By sowdatepicker = By.xpath("(//button[@aria-label='Open calendar'])[3]");
       public By sowdate = By.xpath("//div[normalize-space()='14']");
       public By paymentterms = By.xpath("//select[@id='PaymentTerms']");
       public By paymenttermsselect = By.xpath("//option[@value='3: 2']");
       public By paymentmilestone = By.xpath("//input[@id='BillingMilestoneName']");
       public By milestonedatepicker = By.xpath("(//button[@aria-label='Open calendar'])[4]");
       public By sowtype = By.xpath("//select[@id='SowTypeName']");
       public By sowtypeselect = By.xpath("//option[normalize-space()='Amount']");
       public By sowamount = By.xpath("//input[@placeholder='Enter Sow Amount']");
       public By sowaddbutton = By.xpath("//button[@class='btn btn-rounded btn-primary mb-4 ng-star-inserted']//i[@class='fas fa-plus-circle']");
       public By sowsavebutton = By.xpath("(//button[@title='SaveNext'][normalize-space()='Save & Next'])[2]");
       public By module = By.xpath("//mat-panel-title[normalize-space()='Work Breakdown Structure']");
       public By adddefaultmodule=By.xpath("//button[normalize-space()='Add Default Module']");
       public By selectallmodule = By.xpath("//input[@class='mr-2 mb-2']");
       public By moduleokbutton = By.xpath("//button[normalize-space()='OK']");
       public By modulesave = By.xpath("(//button[@title='SaveNext'][normalize-space()='Save & Next'])[7]");
       public By projectsubmit = By.xpath("//i[@title='Submit']");
//savedprojectrequests
       public By savedprojectrequests = By.xpath("//a[@href='#/project/savedProjectRequestList']");
       public By savedproselect = By.xpath("//tbody/tr[1]/td[1]");
       public By businessunitcolumn = By.xpath("//span[normalize-space()='BusinessUnit']");
       public By departmentcolumn = By.xpath("//span[normalize-space()='Department']");
       public By projectmanagercolumnn = By.xpath("//span[normalize-space()='Project Manager']");
       public By accountmanagercolumn = By.xpath("//span[normalize-space()='Account Manager']");
       public By submittedprojectrequests = By.xpath("//a[@href='#/project/submittedProjectRequestList']");
       public By Projectquickonboard = By.xpath("//a[@href='#/project/quickOnBoardProject']");
       public By submitproselect = By.xpath("//tbody/tr[1]/td[1]");
       public By clientcontactperson = By.xpath("//input[@id='ContactPerson']");
       public By clientemail = By.xpath("//input[@id='Email']");
       public By clientcontactnumbercode = By.xpath("//input[@name='CountryCode']");
       public By clientcontactnumber = By.xpath("//input[@id='ContactNumber']");
       public By maxbill = By.xpath("//input[@id='MaxBillableHours']");
       public By checkboxtick = By.xpath("//input[@id='IsIHereBy']");
       public By delete1 = By.xpath("//body[1]/app-root[1]/block-ui[1]/app-admin-layout-sidebar-large[1]/div[1]/div[3]/app-quick-on-board-project[1]/div[3]/form[1]/div[1]/div[1]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[5]/i[2]");
       public By delete2 = By.xpath("//body[1]/app-root[1]/block-ui[1]/app-admin-layout-sidebar-large[1]/div[1]/div[3]/app-quick-on-board-project[1]/div[3]/form[1]/div[1]/div[1]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[5]/i[2]");
       public By sowcurrency = By.xpath("//select[@id='Currency']");
       public By sowcurrencyinr = By.xpath("//option[normalize-space()='INR']");
       public By projecttype1 = By.xpath("//select[@id='ProjectType']");
       public By projecttypeselect = By.xpath("//option[normalize-space()='Fixed Price']");
       public By projectstdate = By.xpath("/(//button[@aria-label='Open calendar'])[1]");
       public By projectenddate1 = By.xpath("(//button[@aria-label='Open calendar'])[2]");
       public By projectextensionrequest = By.xpath("//a[@href='#/project/ProjectExtensionRequest']");
       public By projectnameextension = By.xpath("//input[@id='ProjectName']");
       public By projectnameextensionselect =By.xpath("//span[contains(text(),'Nw')]");
       public By extensiondate = By.xpath("//input[@id='DateRevEnd']");
       //public By extensionselectmandy = By.xpath("//button[@aria-label='Choose month and year']");
       //public By extensionyear = By.xpath("//div[normalize-space()='2026']"); 
       //public By extensionmonth = By.xpath("//div[normalize-space()='JAN']"); 
       //public By extensiondate = By.xpath("//div[normalize-space()='19']");
       public By extensionreason = By.xpath("(//span[contains(text(),'Yes')])[2]");
       public By extensionreason1 = By.xpath("(//span[contains(text(),'Yes')])[3]");
       public By extensionreasonselect = By.xpath("(//span[contains(text(),'Increase')])[1]");
       public By extensionreasonselect1 = By.xpath("(//span[contains(text(),'Increase')])[2]");
       public By extensioncomment= By.xpath("//textarea[@id='Comments']");
       public By checkboxextension=By.xpath("//input[@id='IsIHereBy']");
       public By extensionsubmit = By.xpath("//button[normalize-space()='Submit']");
       public By support = By.xpath("//option[normalize-space()='Support']");
       public By subtype = By.xpath("//label[normalize-space()='Sub Type']");
      // public By //body/app-root/block-ui/app-admin-layout-sidebar-large[@class='ng-star-inserted']/div[@class='app-admin-wrap layout-sidebar-large']/div[@class='main-content-wrap d-flex flex-column sidenav-open']/app-projectrequests[@class='ng-star-inserted']/div[@class='ng-star-inserted']/div/div[@class='project-request-form']/form[@class='ng-untouched ng-pristine ng-valid']/div[@class='card mb-2']/div[@class='card-body']/div[@class='project-details']/form[@id='projectForm']/div[@class='project-details-forms']/div[@class='left-wrap']/div[1]/div[1]/div[1]/label[1]
       public By billable = By.xpath("//input[@id='MaxBillableHoursDefault']");
       public By milestonename = By.xpath("//input[@id='BillingSupportFixedPriceName']");
       public By datemile = By.xpath("//div[@class='col-lg-4']//button[@aria-label='Open calendar']");
       public By datemileselect = By.xpath("//div[normalize-space()='26']");
       public By milehours = By.xpath("//input[@id='MaxBillableHours1']");
       public By miletype = By.xpath("//select[@id='SowTypeName']");
       public By miletypeselect = By.xpath("//option[normalize-space()='Amount']");
       public By mileamount=By.xpath("//input[@id='SowAmount1']");
       public By mileadd = By.xpath("//button[@class='btn btn-primary btn-rounded mr-2 ng-star-inserted']");
       public By monthly = By.xpath("//option[normalize-space()='Fixed Monthly']");
}
       
       
       


