package com.Pages_ProjectModule;
import java.util.Map;

import org.testng.ITestContext;

import com.BasePackage.Base_Class;
import com.Page_Repositary.PageRepositary_ProjectModule;
import com.aventstack.extentreports.Status;
import com.extentReports.ExtentTestManager;
public class Project_Projecttypesfixed  extends Base_Class{
	PageRepositary_ProjectModule PageRepositary= new PageRepositary_ProjectModule();
	
    
	  public boolean clickOnProjectsubModule(Map<Object, Object> testdata, ITestContext context) throws InterruptedException {
		  
		  String projectname=testdata.get("Projectname").toString();
		  String requestdate = testdata.get("rdate").toString();

	         

		  ScrollUntilElementVisible(PageRepositary.clickOnproject);
		  ExtentTestManager.getTest().log(Status.PASS,"Project module is displayed");
	         Thread.sleep(3000);
	       click(PageRepositary.clickOnproject);
	       Thread.sleep(1000);
	       ExtentTestManager.startTest(" TC1 Navigating to projects submenu");
	       ExtentTestManager.getTest().log(Status.PASS,"Navigating to project submodule");
	       click(PageRepositary.projects);
	       Thread.sleep(1000);
	       ExtentTestManager.endTest();
	       ExtentTestManager.getTest().log(Status.PASS,"click on create project");
	       click(PageRepositary.createproject);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 2 providing details to create a project request");
	       ExtentTestManager.getTest().log(Status.PASS,"providing details for creating a new project");
	       click(PageRepositary.projectclientname);
	       input(PageRepositary.projectclientname,"cliento");
	       Thread.sleep(1000);
	       click(PageRepositary.clientoneselect);
	       click(PageRepositary.projectname);
	       input(PageRepositary.projectname,projectname);
	       Thread.sleep(5000);
	       click(PageRepositary.projectbusinessunit);
	       input(PageRepositary.projectbusinessunit,"india");
	       click(PageRepositary.projectbusinessunitselect);
	       Thread.sleep(1000);
	       click(PageRepositary.projectdivision);
	       input(PageRepositary.projectdivision,"crm");
	       Thread.sleep(1000);
	       click(PageRepositary.projectdivisionselect);
	       click(PageRepositary.projectdepartment);
	       input(PageRepositary.projectdepartment,"acc");
	       click(PageRepositary.projectdepartmentselect);
	       click(PageRepositary.projecttechnology);
	       input(PageRepositary.projecttechnology,"acc");
	       click(PageRepositary.projecttechnologyselect);
	       click(PageRepositary.projecttype);
	       click(PageRepositary.projecttypefixedprice);
	       Thread.sleep(1000);
	       click(PageRepositary.subtype);
	       Thread.sleep(1000);
	       ExtentTestManager.getTest().log(Status.PASS,"selecting project as fixed-monthly project type");
	       click(PageRepositary.monthly);
	       Thread.sleep(1000);
	       Thread.sleep(1000);
	       click(PageRepositary.billable);
	       input(PageRepositary.billable,"200");
	       click(PageRepositary.projectbillabledropdown);
	       click(PageRepositary.projectbillableselect);
	       click(PageRepositary.projectstartdate);
	       click(PageRepositary.projectstartdateselect);
	       click(PageRepositary.projectenddate);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.projectenddateselect);
	       click(PageRepositary.projectcurrentphase);
	       click(PageRepositary.projectcurrentphaseselect);
	       click(PageRepositary.projectdirector);
	       click(PageRepositary.searchperson);
	       input(PageRepositary.searchperson,"clement");
	       click(PageRepositary.projectdirectorselect);
	       click(PageRepositary.okbutton);
	       click(PageRepositary.projectmanager);
	       click(PageRepositary.searchperson);
	       input(PageRepositary.searchperson,"clement");
	       click(PageRepositary.projectmanagerselect);
	       click(PageRepositary.okbutton);
	       click(PageRepositary.projectaccountmanager);
	       click(PageRepositary.projectaccountmanagerselect);
	       click(PageRepositary.okbutton);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 3 saving project request");
	       ExtentTestManager.getTest().log(Status.PASS,"saving a project request");
	       ScrollUntilElementVisible(PageRepositary.projectsaveandnext);
	       click(PageRepositary.projectsaveandnext);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 4 validating other fields are enabled only after saving");
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 5 providing billing details");
	       ExtentTestManager.getTest().log(Status.PASS,"saving billing details of project request");
	       click(PageRepositary.projectbillingdetail);
	       ExtentTestManager.endTest();
	       ScrollUntilElementVisible(PageRepositary.billingsave);
	       click(PageRepositary.currencydrop);
	       click(PageRepositary.ind);
	       click(PageRepositary.currencyvalue);
	       input(PageRepositary.currencyvalue,"20000");
	       click(PageRepositary.sowdatepicker);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.sowdate);
	       click(PageRepositary.paymentterms);
	       click(PageRepositary.paymenttermsselect);
	       //click(PageRepositary.milestonename);
	       //input(PageRepositary.milestonename,"m1");
	       //click(PageRepositary.datemile);
	       //click(PageRepositary.nextmonth);
	       //click(PageRepositary.datemileselect);
	       //click(PageRepositary.miletype);
	       //click(PageRepositary.miletypeselect);
	       //click(PageRepositary.mileamount);
	       //input(PageRepositary.mileamount,"20000");
	       //click(PageRepositary.mileadd);
	       ScrollUntilElementVisible(PageRepositary.module);
	       ExtentTestManager.startTest("TC 6 saving billing details");
	       Hover(PageRepositary.sowsavebutton);
	       click(PageRepositary.sowsavebutton);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 7 providing module details");
	       ExtentTestManager.getTest().log(Status.PASS,"providing module details");
	       ScrollUntilElementVisible(PageRepositary.module);
	       click(PageRepositary.module);
	       click(PageRepositary.adddefaultmodule);
	       click(PageRepositary.selectallmodule);
	       click(PageRepositary.moduleokbutton);
	       ExtentTestManager.endTest();
	       Thread.sleep(1000);
	       ExtentTestManager.startTest("TC 8 saving module details");
	       ExtentTestManager.getTest().log(Status.PASS,"saving module details");
	       ScrollUntilElementVisible(PageRepositary.modulesave);
	       click(PageRepositary.modulesave);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 9 submitting project creation request");
	       ExtentTestManager.getTest().log(Status.PASS,"saving project request");
	       ScrollUntilElementVisible(PageRepositary.projectsubmit);
	       ExtentTestManager.getTest().log(Status.PASS,"submitting the project request");
	       click(PageRepositary.projectsubmit);
	       ExtentTestManager.endTest();
	       handlePopupDesktop();
	       return true;
	  }}