package com.Pages_ProjectModule;
import java.util.Map;

import org.testng.ITestContext;

import com.BasePackage.Base_Class;
import com.Page_Repositary.PageRepositary_ProjectModule;
import com.aventstack.extentreports.Status;
import com.extentReports.ExtentTestManager;
public class Project_Project  extends Base_Class{
	PageRepositary_ProjectModule PageRepositary= new PageRepositary_ProjectModule();
	
    
	  public boolean clickOnProjectsubModule(Map<Object, Object> testdata, ITestContext context) throws InterruptedException {
		  
		  String projectname=testdata.get("Projectname").toString();
		  String requestdate = testdata.get("rdate").toString();

	         

		  ScrollUntilElementVisible(PageRepositary.clickOnproject);
		  ExtentTestManager.getTest().log(Status.PASS,"Project module is displayed");
	         Thread.sleep(3000);
	       click(PageRepositary.clickOnproject);
	       Thread.sleep(1000);
	       ExtentTestManager.startTest(" TC1 Navigating to projects submenu");
	       click(PageRepositary.projects);
	       Thread.sleep(1000);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC2 Clicking on projectlist");
	       click(PageRepositary.Projectlist);
	       ExtentTestManager.endTest();
	       ElementDisplayedprojectlist();
	     //search in project saved page
	       ExtentTestManager.startTest("TC 17 search is available in saved client request page");
	       click(PageRepositary.searchicon);
	       click(PageRepositary.searchfield);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC_18 search is performed");
	       input(PageRepositary.searchfield,"clien");
	       click(PageRepositary.searchbutton);
	       ExtentTestManager.getTest().log(Status.PASS,"search performed");
	       Thread.sleep(2000);
	       click(PageRepositary.searchclose);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest(" TC 19 Downloading projectlist details");
	       click(PageRepositary.downloadicon);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC20 Displaying project details");
	       click(PageRepositary.selectproject);
	       Thread.sleep(1000);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 21 verifying close button");
	       click(PageRepositary.closebutton);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 22 opening create project page");
	       ScrollUntilElementVisible(PageRepositary.clickOnproject);
	       click(PageRepositary.clickOnproject);
	       click(PageRepositary.projects);
	       click(PageRepositary.createproject);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 23 providing details to create a project request");
	       click(PageRepositary.projectclientname);
	       input(PageRepositary.projectclientname,"cliento");
	       Thread.sleep(1000);
	       click(PageRepositary.clientoneselect);
	       click(PageRepositary.projectname);
	       input(PageRepositary.projectname,projectname);
	       Thread.sleep(5000);
	       click(PageRepositary.projectbusinessunit);
	       input(PageRepositary.projectbusinessunit,"india");
	       click(PageRepositary.projectbusinessunitselect);
	       Thread.sleep(1000);
	       click(PageRepositary.projectdivision);
	       input(PageRepositary.projectdivision,"crm");
	       Thread.sleep(1000);
	       click(PageRepositary.projectdivisionselect);
	       click(PageRepositary.projectdepartment);
	       input(PageRepositary.projectdepartment,"acc");
	       click(PageRepositary.projectdepartmentselect);
	       click(PageRepositary.projecttechnology);
	       input(PageRepositary.projecttechnology,"acc");
	       click(PageRepositary.projecttechnologyselect);
	       click(PageRepositary.projecttype);
	       click(PageRepositary.projecttypefixedprice);
	       click(PageRepositary.projectbillablehours);
	       input(PageRepositary.projectbillablehours,"200");
	       click(PageRepositary.projectbillabledropdown);
	       click(PageRepositary.projectbillableselect);
	       click(PageRepositary.projectstartdate);
	       click(PageRepositary.projectstartdateselect);
	       click(PageRepositary.projectenddate);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.projectenddateselect);
	       click(PageRepositary.projectcurrentphase);
	       click(PageRepositary.projectcurrentphaseselect);
	       click(PageRepositary.projectdirector);
	       click(PageRepositary.searchperson);
	       input(PageRepositary.searchperson,"clement");
	       click(PageRepositary.projectdirectorselect);
	       click(PageRepositary.okbutton);
	       click(PageRepositary.projectmanager);
	       click(PageRepositary.searchperson);
	       input(PageRepositary.searchperson,"clement");
	       click(PageRepositary.projectmanagerselect);
	       click(PageRepositary.okbutton);
	       click(PageRepositary.projectaccountmanager);
	       click(PageRepositary.projectaccountmanagerselect);
	       click(PageRepositary.okbutton);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 24 saving project request");
	       ScrollUntilElementVisible(PageRepositary.projectsaveandnext);
	       click(PageRepositary.projectsaveandnext);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 25 validating other fields are enabled only after saving");
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 26 providing billing details");
	       click(PageRepositary.projectbillingdetail);
	       ExtentTestManager.endTest();
	       ScrollUntilElementVisible(PageRepositary.billingsave);
	       click(PageRepositary.currencydrop);
	       click(PageRepositary.ind);
	       click(PageRepositary.currencyvalue);
	       input(PageRepositary.currencyvalue,"20000");
	       click(PageRepositary.sowdatepicker);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.sowdate);
	       click(PageRepositary.paymentterms);
	       click(PageRepositary.paymenttermsselect);
	       click(PageRepositary.paymentmilestone);
	       input(PageRepositary.paymentmilestone,"m1");
	       click(PageRepositary.milestonedatepicker);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.sowdate);
	       click(PageRepositary.sowtype);
	       click(PageRepositary.sowtypeselect);
	       click(PageRepositary.sowamount);
	       input(PageRepositary.sowamount,"20000");
	       click(PageRepositary.sowaddbutton);
	       ScrollUntilElementVisible(PageRepositary.module);
	       ExtentTestManager.startTest("TC 27 saving billing details");
	       Hover(PageRepositary.sowsavebutton);
	       click(PageRepositary.sowsavebutton);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 28 providing module details");
	       ScrollUntilElementVisible(PageRepositary.module);
	       click(PageRepositary.module);
	       click(PageRepositary.adddefaultmodule);
	       click(PageRepositary.selectallmodule);
	       click(PageRepositary.moduleokbutton);
	       ExtentTestManager.endTest();
	       Thread.sleep(1000);
	       ExtentTestManager.startTest("TC 29saving module details");
	       ScrollUntilElementVisible(PageRepositary.modulesave);
	       click(PageRepositary.modulesave);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 30 submitting project creation request");
	       ScrollUntilElementVisible(PageRepositary.projectsubmit);
	       click(PageRepositary.projectsubmit);
	       ExtentTestManager.endTest();
	       handlePopupDesktop();
	       ExtentTestManager.startTest("TC 31navigating to saved project request");
	       ScrollUntilElementVisible(PageRepositary.clickOnproject);
		   Thread.sleep(2000);
		   click(PageRepositary.clickOnproject);
		   Thread.sleep(1000);
		   click(PageRepositary.projects);
		   Thread.sleep(2000);
		   click(PageRepositary.savedprojectrequests);
	       ExtentTestManager.endTest();
		   Thread.sleep(1000);
	       ExtentTestManager.startTest("validating saved project request page");
	       ElementDisplayedsavedprojectrequests();
	       ExtentTestManager.endTest();
	       
	  //search in project saved page
	       ExtentTestManager.startTest("TC_43 search is available in saved project request page");
	       click(PageRepositary.searchicon);
	       click(PageRepositary.searchfield);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC_44 search is performed");
	       input(PageRepositary.searchfield,"pro");
	       click(PageRepositary.searchbutton);
	       ExtentTestManager.getTest().log(Status.PASS,"search performed");
	       Thread.sleep(2000);
	       click(PageRepositary.searchclose);
	       ExtentTestManager.endTest();
	       click(PageRepositary.savedproselect);
	       Thread.sleep(2000);
	       click(PageRepositary.closebutton);
	       //submitted requests
	       ScrollUntilElementVisible(PageRepositary.clickOnproject);
		   Thread.sleep(2000);
		   ExtentTestManager.startTest("tc 45 Navigating to submitted project page");
		   click(PageRepositary.clickOnproject);
		   Thread.sleep(1000);
		   click(PageRepositary.projects);
		   Thread.sleep(2000);
		   ExtentTestManager.endTest();
		   click(PageRepositary.submittedprojectrequests);
	       ExtentTestManager.endTest();
		   Thread.sleep(1000);
	       ExtentTestManager.startTest("TC 46 validating submitted project request page");
	       ElementDisplayedsubmittedprojectrequests();
	       ExtentTestManager.endTest();
	     //search in project submitted page
	       ExtentTestManager.startTest("TC_58 search is available in submitted project request page");
	       click(PageRepositary.searchicon);
	       click(PageRepositary.searchfield);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC_59 search is performed");
	       input(PageRepositary.searchfield,"pro");
	       click(PageRepositary.searchbutton);
	       ExtentTestManager.getTest().log(Status.PASS,"search performed");
	       Thread.sleep(2000);
	       click(PageRepositary.searchclose);
	       ExtentTestManager.endTest();
	       click(PageRepositary.submitproselect);
	       Thread.sleep(2000);
	       click(PageRepositary.closebutton);
	       ExtentTestManager.startTest("tc 60 Navigating to quick on board project page");
	       ScrollUntilElementVisible(PageRepositary.clickOnproject);
		   Thread.sleep(2000);
		   click(PageRepositary.clickOnproject);
		   Thread.sleep(1000);
		   click(PageRepositary.projects);
		   Thread.sleep(2000);
		   ExtentTestManager.endTest();
		   click(PageRepositary.Projectquickonboard);
	       ExtentTestManager.endTest();
		   Thread.sleep(1000);
	       ExtentTestManager.startTest("tc 61validating project quick on board page");
	       ExtentTestManager.startTest("tc 62creating a new quick on board project request");
	       click(PageRepositary.projectclientname);
	       input(PageRepositary.projectclientname,"cliento");
	       Thread.sleep(1000);
	       click(PageRepositary.clientoneselect);
	       click(PageRepositary.projectname);
	       input(PageRepositary.projectname,"projectquick");
	       click(PageRepositary.sowcurrency);
	       click(PageRepositary.sowcurrencyinr);
	       click(PageRepositary.currencyvalue);
	       input(PageRepositary.currencyvalue,"20000");
	       click(PageRepositary.projecttype1);
	       click(PageRepositary.projecttypeselect);
	       click(PageRepositary.projectstartdate);
	       click(PageRepositary.projectstartdateselect);
	       click(PageRepositary.projectenddate);
	       click(PageRepositary.nextmonth);
	       click(PageRepositary.projectenddateselect);
	       click(PageRepositary.maxbill);
	       input(PageRepositary.maxbill,"300");
	       ScrollUntilElementVisible(PageRepositary.submitbutton);
	       click(PageRepositary.adddefaultmodule);
	       click(PageRepositary.delete1);
	       click(PageRepositary.delete1);
	       ExtentTestManager.endTest();
	       ExtentTestManager.startTest("TC 63 submitting quick on board project request");
	       click(PageRepositary.checkboxtick);
	       ScrollUntilElementVisible(PageRepositary.submitbutton);
	       click(PageRepositary.submitbutton);
	       ExtentTestManager.endTest();
	       handlePopupDesktop();
	       ScrollUntilElementVisible(PageRepositary.clickOnproject);
		   Thread.sleep(3000);
		   click(PageRepositary.clickOnproject);
		   Thread.sleep(1000);
		   ExtentTestManager.startTest(" TC 64 Navigating to project extension request");
	       click(PageRepositary.projects);
	       Thread.sleep(1000);
	       ExtentTestManager.endTest();
	       click(PageRepositary.projectextensionrequest);
	       Thread.sleep(1000);
	       ExtentTestManager.startTest("TC 65 project extension request page is displayed");
	       ExtentTestManager.endTest();
	       click(PageRepositary.projectnameextension);
	       ExtentTestManager.startTest("TC 66 verify if its able to select the project for extension");
	       ExtentTestManager.endTest();
	       click(PageRepositary.projectnameextensionselect);
	       ExtentTestManager.startTest("TC 67 verify if its able to select project extension date");
	       ExtentTestManager.endTest();
	       input(PageRepositary.extensiondate,requestdate);
	      // click(PageRepositary.extensiondatepicker);
	      // click(PageRepositary.extensionselectmandy);
	       //click(PageRepositary.extensionyear);
	      // click(PageRepositary.extensionmonth);
	      // click(PageRepositary.extensiondate);
	       ExtentTestManager.startTest("TC 68 verify if its able to select the reason for project extension");
	       ExtentTestManager.endTest();
	       click(PageRepositary.extensionreason);
	       ExtentTestManager.startTest("TC 69 verify if its able to select the impact of the reason for extension of the project");
	       ExtentTestManager.endTest();
	       ScrollUntilElementVisible(PageRepositary.extensionreasonselect);
	       click(PageRepositary.extensionreasonselect);
	       ExtentTestManager.startTest("TC 70 verify if its able to provide comments for project extension request");
	       ExtentTestManager.endTest();
	       ScrollUntilElementVisible(PageRepositary.extensionsubmit);
	       click(PageRepositary.extensioncomment);
	       input(PageRepositary.extensioncomment,"project extension request");
	       ExtentTestManager.startTest("TC 71 verify if its able to check documment field");
	       ExtentTestManager.endTest();
	       click(PageRepositary.checkboxextension);
	       ExtentTestManager.startTest("TC 72 verify its able to submit the project extension request");
	       ExtentTestManager.endTest();
	       click(PageRepositary.extensionsubmit);
	       handlePopupDesktop();
	       return true;
	  }
	  public boolean ElementDisplayedprojectlist() throws InterruptedException {
		    ExtentTestManager.startTest("TC3 verifying project code");
			boolean flag1=ElementDisplayed(PageRepositary.projectcodecolumn);
			System.out.println(" verifying project code ");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 4 verifying project name");
			boolean flag2=ElementDisplayed(PageRepositary.projectnamecolumn);
			System.out.println("verifying project name");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 5 verifying client name");
			boolean flag3=ElementDisplayed(PageRepositary.clientnamecolumn);
			System.out.println("verifying client name ");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 6 verifying project director");
			boolean flag4=ElementDisplayed(PageRepositary.projectdirectorcolumn);
			System.out.println("verifying project director");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 7 verifying project manager");
			boolean flag5=ElementDisplayed(PageRepositary.projectmanagercolumn);
			System.out.println("verifying project manager");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 8 verifying billability");
			boolean flag6=ElementDisplayed(PageRepositary.projectmanagercolumn);
			System.out.println("verifying billability");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 9 verifying project type");
			boolean flag7=ElementDisplayed(PageRepositary.projecttypecolumn);
			System.out.println("verifying project type");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 10 verifying expected start date");
			boolean flag8=ElementDisplayed(PageRepositary.expectstartdatecolumn);
			System.out.println("verifying expected start date");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 11 verifying start date");
			boolean flag9=ElementDisplayed(PageRepositary.startdatecolumn);
			System.out.println("verifying start date");
			ExtentTestManager.endTest();
			ExtentTestManager.startTest(" TC 12addnewbutton is displayed");
			boolean flag10=ElementDisplayed(PageRepositary.addnewbutton);
			System.out.println("addnewbutton is displayed "+ flag8);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 13 searchicon is displayed");
			boolean flag11=ElementDisplayed(PageRepositary.searchicon);
			System.out.println("searchicon is displayed "+ flag9);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 14 downloadicon is displayed");
			boolean flag12=ElementDisplayed(PageRepositary.downloadicon);
			System.out.println("downloadicon is displayed "+ flag10);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 15 pagination is displayed");
			boolean flag13=ElementDisplayed(PageRepositary.pagination);
			System.out.println("pagination is displayed "+ flag11);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 16 totalitems is displayed");
			boolean flag14=ElementDisplayed(PageRepositary.totalitems);
			System.out.println("totalitems is displayed "+ flag12);
			ExtentTestManager.endTest();
			
			
			boolean flag= flag1 & flag2 & flag3 & flag4 & flag5 & flag6 & flag7 & flag8 & flag9 & flag10 & flag11 & flag12 & flag13 & flag14;
					return flag;
		}
	  public boolean ElementDisplayedsubmittedprojectrequests() throws InterruptedException {
		    ExtentTestManager.startTest("TC 47 project name is displayed");
			boolean flag1=ElementDisplayed(PageRepositary.projectnamecolumn);
			System.out.println("project name is displayed "+ flag1);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 48 project code is displayed");
			boolean flag2=ElementDisplayed(PageRepositary.projectcodecolumn);
			System.out.println("project code is displayed "+ flag2);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 49 clientname is displayed");
			boolean flag3=ElementDisplayed(PageRepositary.Clientnamecolumn);
			System.out.println("Clientname is displayed "+ flag3);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 50 Business unit is displayed");
			boolean flag4=ElementDisplayed(PageRepositary.businessunitcolumn);
			System.out.println("business unit is displayed "+ flag4);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 51 department is displayed");
			boolean flag5=ElementDisplayed(PageRepositary.departmentcolumn);
			System.out.println("department is displayed "+ flag5);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 52 project manager is displayed");
			boolean flag6=ElementDisplayed(PageRepositary.projectmanagercolumnn);
			System.out.println("project manager is displayed"+ flag6);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 53 account manager is displayed");
			boolean flag7=ElementDisplayed(PageRepositary.accountmanagercolumn);
			System.out.println("account manager is displayed "+ flag7);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 54 addnewbutton is displayed  is displayed");
			boolean flag8=ElementDisplayed(PageRepositary.addnewbutton);
			System.out.println("addnewbutton is displayed "+ flag8);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 55 searchicon is displayed is displayed");
			boolean flag9=ElementDisplayed(PageRepositary.searchicon);
			System.out.println("searchicon is displayed "+ flag9);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC_56 pagination is displayed");
			boolean flag10=ElementDisplayed(PageRepositary.pagination);
			System.out.println("pagination is displayed "+ flag10);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC_57 total items is displayed");
			boolean flag11=ElementDisplayed(PageRepositary.totalitems);
			System.out.println("totalitems is displayed "+ flag11);
			ExtentTestManager.endTest();
			boolean flag= flag1 & flag2 & flag3 & flag4 & flag5 & flag6 & flag7 & flag8 & flag9 & flag10 & flag11;
					return flag;
		}
	  public boolean ElementDisplayedsavedprojectrequests() throws InterruptedException {
		    ExtentTestManager.startTest("TC 32 project name is displayed");
			boolean flag1=ElementDisplayed(PageRepositary.projectnamecolumn);
			System.out.println("project name is displayed "+ flag1);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 33 project code is displayed");
			boolean flag2=ElementDisplayed(PageRepositary.projectcodecolumn);
			System.out.println("project code is displayed "+ flag2);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 34 clientname is displayed");
			boolean flag3=ElementDisplayed(PageRepositary.Clientnamecolumn);
			System.out.println("Clientname is displayed "+ flag3);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 35 Business unit is displayed");
			boolean flag4=ElementDisplayed(PageRepositary.businessunitcolumn);
			System.out.println("business unit is displayed "+ flag4);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 36 department is displayed");
			boolean flag5=ElementDisplayed(PageRepositary.departmentcolumn);
			System.out.println("department is displayed "+ flag5);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 37 project manager is displayed");
			boolean flag6=ElementDisplayed(PageRepositary.projectmanagercolumnn);
			System.out.println("project manager is displayed"+ flag6);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 38 account manager is displayed");
			boolean flag7=ElementDisplayed(PageRepositary.accountmanagercolumn);
			System.out.println("account manager is displayed "+ flag7);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 39 addnewbutton is displayed  is displayed");
			boolean flag8=ElementDisplayed(PageRepositary.addnewbutton);
			System.out.println("addnewbutton is displayed "+ flag8);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC 40 searchicon is displayed is displayed");
			boolean flag9=ElementDisplayed(PageRepositary.searchicon);
			System.out.println("searchicon is displayed "+ flag9);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC_41 pagination is displayed");
			boolean flag10=ElementDisplayed(PageRepositary.pagination);
			System.out.println("pagination is displayed "+ flag10);
			ExtentTestManager.endTest();
			ExtentTestManager.startTest("TC_42 total items is displayed");
			boolean flag11=ElementDisplayed(PageRepositary.totalitems);
			System.out.println("totalitems is displayed "+ flag11);
			ExtentTestManager.endTest();
			boolean flag= flag1 & flag2 & flag3 & flag4 & flag5 & flag6 & flag7 & flag8 & flag9 & flag10 & flag11;
					return flag;
		}
}
